#!/bin/bash

# note: must be run from the project root folder

# set env variables
envFile="$PWD/.env"
source "$envFile"
BOOTSTRAP_SERVER=$BOOTSTRAP_SERVER
DEPOSIT_GROUP=$DEPOSIT_GROUP
DEPOSIT_TOPIC=$DEPOSIT_TOPIC
DEPOSIT_BUCKET_NAME=$DEPOSIT_BUCKET_NAME
DEPOSIT_KEY_NAME=$DEPOSIT_KEY_NAME
K_AWS_ACCESS_KEY_ID=$K_AWS_ACCESS_KEY_ID
K_AWS_SECRET_ACCESS_KEY=$K_AWS_SECRET_ACCESS_KEY
K_AWS_SESSION_TOKEN=$K_AWS_SESSION_TOKEN
K_AWS_EXPIRATION=$K_AWS_EXPIRATION
HEADER_ACCEPT=$HEADER_ACCEPT
HEADER_X_API_KEY=$HEADER_X_API_KEY
API_ENDPOINT=$API_ENDPOINT
KAFKA_TYPE=$KAFKA_TYPE
CONFLUENT_KEY=$CONFLUENT_KEY
CONFLUENT_SECRET=$CONFLUENT_SECRET

# build
echo "Compiling."
mvn clean package assembly:single

# run
echo "Executing."
java -Dlogback.configurationFile=./src/main/resources/logback.xml \
	-DBOOTSTRAP_SERVER=$BOOTSTRAP_SERVER \
	-DDEPOSIT_GROUP=$DEPOSIT_GROUP \
	-DDEPOSIT_TOPIC=$DEPOSIT_TOPIC \
	-DDEPOSIT_BUCKET_NAME=$DEPOSIT_BUCKET_NAME \
	-DDEPOSIT_KEY_NAME=$DEPOSIT_KEY_NAME \
	-DK_AWS_ACCESS_KEY_ID=$K_AWS_ACCESS_KEY_ID \
	-DK_AWS_SECRET_ACCESS_KEY=$K_AWS_SECRET_ACCESS_KEY \
	-DK_AWS_SESSION_TOKEN=$K_AWS_SESSION_TOKEN \
	-DK_AWS_EXPIRATION=$K_AWS_EXPIRATION \
	-DHEADER_ACCEPT=$HEADER_ACCEPT \
	-DHEADER_X_API_KEY=$HEADER_X_API_KEY \
	-DAPI_ENDPOINT=$API_ENDPOINT \
	-DKAFKA_TYPE=$KAFKA_TYPE \
	-DCONFLUENT_KEY=$CONFLUENT_KEY \
	-DCONFLUENT_SECRET=$CONFLUENT_SECRET \
	-jar ./target/jpo-aws-depositor-jar-with-dependencies.jar
