name: Docker build

on:
  push:
    branches-ignore:
      - "develop"
      - "master"
      - "release/*"
jobs:
  jpo-s3-deposit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build
        uses: docker/build-push-action@v5
