name: "DockerHub Build and Push"

on:
  push:
    branches:
      - "develop"
      - "master"
      - "release/*"

jobs:
  dockerhub-jpo-s3-deposit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Replcae Docker tag
        id: set_tag
        run: echo "TAG=$(echo ${GITHUB_REF##*/} | sed 's/\//-/g')" >> $GITHUB_ENV
    
      - name: Build
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: usdotjpoode/jpo-s3-deposit:${{ env.TAG }}   
